name: 'Setup Agda'
description: 'Set up a specific version of Agda and its standard library and add the command-line tools to the PATH'
author: 'Orestis Melkonian'
inputs:
  agda-version:
    required: false
    description: 'Version of Agda to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  stdlib-version:
    required: false
    description: 'Version of the Agda standard library to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  libraries:
    required: false
    description: 'Provide extra libraries (from git repositories) to install, e.g. "omelkonian/formal-prelude\n UlfNorell/agda-prelude#compat-2.5.2".'
    default: ''
  build:
    required: false
    description: 'Whether to build the Agda project.'
    default: true
  main:
    required: false
    description: "Entry point for your Agda project without the '.agda' extention, e.g. 'Example/Main'"
    default: 'Main'
  deploy:
    required: false
    description: 'Whether to deploy the Github page, containing the Agda code rendered in HTML.'
    default: false
  token:
    required: false
    description: 'Secret token for deploying to Github Pages, will not deploy if not set to GITHUB_TOKEN.'
  deploy-branch:
    required: false
    description: 'On which branch to deploy the Github page.'
    default: 'gh-pages'
  css:
    required: false
    description: "Optional .css file to use for HTML-rendered Agda code, a path relative to the project's root."
  rts:
    required: false
    description: 'Optional RTS options for GHC.'
    default: ''
  ribbon:
    required: false
    description: 'Include a Github ribbon on every generated HTML file.'
    default: false
  ribbon-msg:
    required: false
    description: 'Ribbon message to display.'
    default: 'Source code on Github'
  ribbon-color:
    required: false
    description: 'Ribbon color (in CSS-compliant format).'
    default: '#333'

runs:
  using: 'node12'
  main: 'dist/index.js'
  pre: 'dist/setup-haskell/main/index.js'
  pre-if: env.HASKELL == 0
