name: build-test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  # test:
  #   name: Unit Tests - ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest] #, macOS-latest, windows-latest]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set Node.js 12
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     # http://www.tiernok.com/posts/2019/faster-npm-installs-during-ci/
  #     - run: npm ci --prefer-offline --no-audit --progress=false
  #     - run: npm test

  install-agda:
    name: Agda ${{ matrix.agda }}, stdlib ${{ matrix.stdlib }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        agda: [latest]
        stdlib: [latest]

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: '8.6.5'
          enable-stack: true
          # stack-no-global: true
          # stack-setup-ghc: true
      - name: Mark Haskell as installed
        run: echo "HASKELL=1" >> $GITHUB_ENV
      - uses: ./
        with:
          agda-version: ${{ matrix.agda }}
          stdlib-version: ${{ matrix.stdlib }}
          libraries: 'omelkonian:formal-prelude'
          main: Example/Test
          token: ${{ secrets.GITHUB_TOKEN }}
